name: kakfa-cluster
kafka:
  version: 3.7.0
  replicas: 3
  config:
    offsetsTopicReplicationFactor: 3
    transactionStateLogReplicationFactor: 3
    transactionStateLogMinIsr: 2
    defaultReplicationFactor: 3
    minInsyncReplicas: 2
    interBrokerProtocolVersion: "3.7"
    storage:
      size: 100Gi
      deleteClaim: false
zookeeper:
  replicas: 3
  storage:
    type: persistent-claim
    size: 100Gi
    deleteClaim: false
entityOperator:
  topicOperator: {}
  userOperator: {}
