name: kakfa-cluster
kafka:
  version: 3.7.0
  replicas: 3
  config:
    offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.7"
      storage:
        size: 100Gi
        deleteClaim: false
zookeeper:
  replicas: 3
  storage:
    type: persistent-claim
    size: 100Gi
    deleteClaim: false
entityOperator:
  topicOperator: {}
  userOperator: {}
